name: CD - Deploy Angular to IIS

on:
  workflow_dispatch: # Manual Trigger

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: C:\inetpub\actions-runner\_work\Downloading

      - name: Stop IIS Server
        run: |
          net stop w3svc
        shell: cmd

      - name: Deploy to IIS
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\angular_app\*" -ErrorAction Ignore
          Copy-Item -Recurse -Force "C:\deploy\angular_build\*" "C:\inetpub\wwwroot\angular_app\"
        shell: powershell

      - name: Restart IIS
        run: iisreset
        shell: cmd
