name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd ASP.Net_Angular/PaymentApp_Angular
          npm install

      - name: Build Angular App
        run: |
          cd ASP.Net_Angular/PaymentApp_Angular
          npm run build -- --configuration=production

      - name: Stop IIS Server
        run: |
          net stop was /y
          net stop w3svc

      - name: Deploy to IIS
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\react_frontend\*" -ErrorAction Ignore
          Copy-Item -Recurse -Force "ASP.Net_Angular/PaymentApp_Angular/dist/*" "C:\inetpub\wwwroot\react_frontend\"

      - name: Start IIS Server
        run: |
          net start w3svc
